FROM debian

RUN apt-get -y update && apt-get install -y \
    universal-ctags && \
    apt-get clean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /bindmount

ENTRYPOINT [ "ctags" ]
